stocks:
  - symbol: NFLX
    period: 5y

output:
  csv: true
  json: true
  sqlite: false
  output_folder: data/output
  raw_folder: data/raw
  clean_folder: data/clean
  sqlite_path: data/db/scraper_data.db
  save_charts: true
  log_file: logs/scraper.log
